package org.dispatchsystem.common.events.domains;

public enum ReasonCode {
    OUTSIDE_PICKUP_RADIUS,
    VEHICLE_CLASS_MISMATCH,
    LUGGAGE_CAPACITY_MISMATCH,
    BOOKING_TYPE_UNSUPPORTED,
    SCHEDULE_UNAVAILABLE,
    DURATION_UNSUPPORTED,
    DRIVER_ALREADY_RESERVED,
    NO_ELIGIBLE_DRIVERS,
    PASSENGER_CANCELLED,
    OFFER_TIMEOUT,
    DRIVER_REJECTED,
    DRIVER_LOCATION_NOT_AVAILABLE,
    INSIDE_PICKUP_RADIUS,
    VEHICLE_CLASS_MATCHED,
    LUGGAGE_CAPACITY_MATCHED,
    BOOKING_TYPE_SUPPORTED,
    SCHEDULE_AVAILABLE,
    DURATION_SUPPORTED,
    DRIVER_IS_AVAILABLE,
    DRIVER_ACCEPTED,
    ALL_OFFERS_EXHAUSTED,


    }
